# -*- coding: utf-8 -*-
"""python_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1laAaIixwpacKsKAtFzocwOBMHManJUYk

# Why Python

Python is an interpreted language with simple syntax. It has many prebuilt libraries to simplify Machine Learning model building process

Since Python is an interpreted language it doesn't required compilation or jar file creation like other programming languages

#Python Basics

## Arithmetic Operations

Python supports all basic arithmetic operations like addition,subtraction, multiplication, division , exponetial, modulus operations etc
"""

10+50

10+50
30+5

"""Printing 2 lines"""

## Printing 2 lines
print(10+50)
print(30+5)

10*5

10 / 2

2 ** 4

7 % 2

"""## Variable Assignmnet

You do not need to declare variable type explicitly. Variable data type will be determined based on the assigned value

Variable name cannot start with number or special character
"""

variable_one = 20

variable_two = "ML NLP"

"""You can ceck the data type using type function"""

#to check the type
type(variable_one)

type(variable_two)

variable_two = 100.5

type(variable_two)

variable_two = 'ML NLP'
variable_two

variable_two = "ML NLP"
variable_two

variable_two = 'ML " NLP'
variable_two

variable_two = "ML ' NLP"
variable_two

"""## List

It is a collection data type to store a sequence of elements

Since Machine Learning is all about data processing you need to understand how to store and retrieve value from a List
"""

var_list = [10,20,30,40]

type(var_list)

"""You can grab elements by specifying index locations"""

var_list[0]

var_list[1]

var_list[2]

var_list[3]

var_list[-1]

var_list[-2]

var_list[-3]

var_list[-4]

"""You can grab a portion of the list by specifying starting and end index. Note that the end index is always excluded. 

For example 1:3 will fetch elements starting with index 1 and up to 3rd element but not including the 3rd element
"""

var_list[1:3]

var_list[:3]

var_list[2:]

another_list = [10,'abc',20]

another_list[1]

another_list[2]

another_list.append(3)

another_list

another_list.pop()

another_list

another_list.pop(1)

another_list

"""## if else elif"""

if 1> 2:
  # loop starts
  print("Inside if block")
  print("Also Inside if block")
  # loop ends
print('outside if block')

if 1 < 2:
  print("Inside if block")
  print("Also Inside if block")
print('outside if block')

if 1 == 2:
  print('inside if block')
elif 3 == 3:
  print('inside elif block')
else:
  print('inside else block')

"""## for loop"""

var_list = [1,2,3,4,5]

for element in var_list:
  print("printing item inside for loop")
  print(element)
  print("now see square")
  print(element**2)

print("We are outside for loop")

var_list = [1,2,3,4,5]

new_list_with_sqaure_values = []

for element in var_list:
    new_list_with_sqaure_values.append(element**2)
print(new_list_with_sqaure_values)

"""Same operation in a single line"""

print([element**2 for element in var_list])

words = ['hello','peter','how','are','you']

newwords = [word for word in words if not word in ['peter','jack']]

newwords

list(range(10))

for element in range(15):
    print(element)

"""## while loop"""

var = 1
while var < 7:
  print("inside while loop")
  print(var)
  var = var+1
print("outside while loop")

"""## function"""

def sample_function(x):
  print("inside function")
  print(x)

sample_function("sample text b")

def calculate_sum(x,y):
  return x+y

out = calculate_sum(2,3)
print(out)

"""## methods
Methods are essentially functions built into objects.
"""

sample_string = 'hello my name is Sam'

type(sample_string)

sample_string.upper()

sample_string.split()

var_list = [10,20,30]

var_list.append(40)

var_list



"""## Writing data to a file on the disk"""

with open("my_file_1.txt","w") as f:
    f.write("sample content 1")

"""## View the file"""

# Linux command to view the list of files in the current directory
!ls

# Linux command to read the content of the file
!cat my_file_1.txt

"""## Append to file"""

with open("my_file_1.txt","a") as f:
    f.write("more content")

# Linux command to read the content of the file
!cat my_file_1.txt

"""## Overwrite File"""

with open("my_file_1.txt","w") as f:
    f.write("new content")

# Linux command to read the content of the file
!cat my_file_1.txt

"""## Read a File"""

with open("my_file_1.txt","r") as f:
    print(f.read())

"""## reference

## https://www.python.org/
"""